### ISSUE TITLE
Custom variable in cloudformation parameters

### ISSUE THREAD

**Issue by sarav2k** [awsdocs/aws-tools-ado-vsts-user-guide#15]
Hello,
I am trying to use pipeline custom variable in cloudformation task's parameters file.
Not sure if this supported but I am unable to successfully get it working.
Anyone has tried this?

Thanks

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
