### ISSUE TITLE
Documentation for "Amazon ECR Pull"

### ISSUE THREAD

**Issue by cbossie** [awsdocs/aws-tools-ado-vsts-user-guide#17]
In the public documentation for the AWS Toolkit for Azure DevOps (https://docs.aws.amazon.com/vsts/latest/userguide/welcome.html), the task "Amazon ECR Pull" is missing.

**Expected behavior**

In the documentation, I would expect that there would be an explanation for the Amazon ECR Pull  task, since the functionality is not identical to the "Amazon ECR Push" task. It most likely belongs in the "General Purpose Tasks" list.

Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
