### ISSUE TITLE
Azure Pipelines yaml key syntax examples

### ISSUE THREAD

**Issue by rrigato** [awsdocs/aws-tools-ado-vsts-user-guide#3]
The docs have examples for the user interface, but not for defining AWS Toolkit for Azure DevOps tasks as YAML, which results in a steep learning curve to begin defining your DevOps Pipelines as code.
Fix #4

**Comment by rrigato** [comment]
@Paul-B-AWS Have you had a chance to review this issue and corresponding PR?

**Comment by Paul-B-AWS** [comment]
Thank you for following up.
I will engage with the appropriate people to increase awareness of the [pull request](https://github.com/awsdocs/aws-tools-ado-vsts-user-guide/pull/4).

**Comment by awsdan** [comment]
Hi there,

Sorry for the continued delay. I hope to have this resolved and pulled into the docs soon.

**Comment by msuter-cbre** [comment]
Hey are you ever going to write this documentation? You said you hope to have it pulled into the docs soon, but that was like over a year ago.

**Comment by rrigato** [comment]
@msuter-cbre Forgive my ignorance if I am mistaken, but I have not seen confirmation that approval was granted to do so? I have been holding off until I received the official go ahead since the original PR took so long to get approved.

**Comment by rrigato** [comment]
@awsdan 
@Paul-B-AWS 
I noticed that the YAML syntax examples for the ```AWSCLI@1``` task from #4 were removed in [this commit](https://github.com/awsdocs/aws-tools-ado-vsts-user-guide/commit/44108471c41c46ed7997812c5fe565ba9c18b650?diff=unified#diff-d194442c54abf6417fd006615af87d25c71f8399622ca0c6c86965cd7fb0495e). 

Are PR's adding YAML syntax still going to be accepted or is a different direction being taken with this documentation?

**Comment by adamjohnstonarm** [comment]
Thanks for creating that that PR @rrigato! Finally found the documentation I was looking for.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
