### ISSUE TITLE
Azure Pipelines Tutorial missing YAML task

### ISSUE THREAD

**Issue by StephenHodgson** [awsdocs/aws-tools-ado-vsts-user-guide#6]
Hi there, I read through the tutorial for the classic pipelines workflow, but was unable to find the YAML workflow for the same task.
https://github.com/awsdocs/aws-tools-ado-vsts-user-guide/blob/master/doc_source/tutorial-s3.md

As the Classic Pipeline workflow is likely to be [deprecated by Microsoft](https://medium.com/@wywywywy/azure-devops-pipeline-choosing-between-yaml-and-classic-ui-b5612c3e211a) and YAML workflows are being promoted as the defacto way to create pipelines, is there any ETA when we will see a YAML tutorial example?

If there is a similar task already available, I wasn't able to find the documentation for it. I was thinking of just writing a simple powershell script to essentially do the same function.

**Comment by justrp** [comment]
@StephenHodgson , seems that duplicates #3 

While there is no doc, probably, you can check params in source code - https://github.com/aws/aws-toolkit-azure-devops/tree/master/Tasks

UPD: you also can create a dummy yaml pipeline, then edit it from ADO web GUI - it will generate yml

**Comment by sbates** [comment]
I feel like "read the source code" as a response to "There is no documentation for the most common way to write ADO pipelines" is not the best response. Are there plans to add any yaml task examples? Having to dig through source code for something as basic as the the name of task I want to write makes this tool incredibly unfriendly. I assume this is an official AWS toolkit which is really surprising.

**Comment by StephenHodgson** [comment]
I guess this is never gonna happen
