### ISSUE TITLE
Set message attribute to SNS message

### ISSUE THREAD

**Issue by AnuragkAnkur** [awsdocs/aws-tools-ado-vsts-user-guide#8]
Hi ,
 I wanted to publish a message from azure build pipeline to aws topic with a custom message attribute. Is there a way to set a custom message attribute using the task ‘ AWS Send SNS or SQS Message task’ ? 
 
Can you please guide/help me ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
