### ISSUE TITLE
s3 Upload Cache Control Expression setting missing documentation

### ISSUE THREAD

**Issue by michaelaplas** [awsdocs/aws-tools-ado-vsts-user-guide#9]
In the `Advanced` section of the the user guide for [s3 uploads](https://github.com/awsdocs/aws-tools-ado-vsts-user-guide/blob/master/doc_source/s3-upload.md) there is no description on the usage for the Cache Control Expression.

Currently its a whole lot of trial and error to figure out the expected syntax of the expression. For simple usage its fairly obvious (as the tooltip in Azure Devops suggests, e.g */.js to target all JS files), however more targeted usage is a bit of a guessing game.

It would be super appreciated if this could be updated with a bit of detail. Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
